### ISSUE TITLE
not actually indexing data

### ISSUE THREAD

**Issue by mschoch** [otoolep/bleve-bench#1]
Unfortunately, the current test doesn't seem to actually be indexing data (looking at boltdb files I only see keys for the back index).  I believe the problem is that the struct only contains data of type []byte, which is not currently supported by bleve.  See https://github.com/otoolep/bleve-bench/blob/master/bleve_indexer.go#L70

Also, the mapping sets up a field named "body", but then the struct being indexed doesn't use that name.   

I would recommend you change that field to type string, and name it Body with struct tag `json:"body"`.

**Comment by otoolep** [comment]
Wow, big issue -- thanks. Let me fix that and re-run the tests.

**Comment by otoolep** [comment]
I do think I had this coded correctly earlier, but made some cosmetic changes to the code, and then forced-pushed. D'oh.

**Comment by otoolep** [comment]
Thanks again @mschoch -- I believe this change fixes it, right?

https://github.com/otoolep/bleve-bench/commit/08cc00d7235e485bd6d8011e8ba478f9a8034364

**Comment by mschoch** [comment]
+1 this works now

**Comment by otoolep** [comment]
Thanks again @mschoch -- that was a really big deal. :-)

**Comment by mschoch** [comment]
Sure no problem, I uncovered it while looking into that panic you reported.
